# # peticion para ver los pokemons
# GET http://localhost:1234/pokemon/ditto

# peticion para crear un pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type":"normal",
    "moves":[
        "transform"
    ]
}